import React,{useState,useEffect,useRef} from 'react';
import mapImage from './campus-map-osm';
import surroundingMap from './campus-surrounding-osm';
import worldMap from './world-map-osm';
import './map.css';
export type Pin={name:string;group:'Outlet'|'Mess';lat:number;lng:number;url:string;note?:string};
export const pins:Pin[]=[
 {name:'Gajalakshmi',group:'Outlet',lat:15.3913574,lng:73.8774977,url:'https://www.google.com/maps/search/?api=1&query=Gajalakshmi+Snacks&query_place_id=ChIJR_hUeze4vzsR_2l4NoBQy8Y',note:'Listed as Gajalakshmi Snacks'},
 {name:'Food King',group:'Outlet',lat:15.3911827,lng:73.8803976,url:'https://www.google.com/maps/search/?api=1&query=FoodKing+Goa&query_place_id=ChIJhf-W4za4vzsReN8Q14tNNsw'},
 {name:'INS',group:'Outlet',lat:15.3925298,lng:73.8790965,url:'https://www.google.com/maps/search/?api=1&query=Ice+%27n%27+Spice&query_place_id=ChIJkVQZpDe4vzsRvjbc7ReaVOs',note:"Listed as Ice 'n' Spice"},
 {name:'Nescafe',group:'Outlet',lat:15.3929813,lng:73.8802799,url:'https://www.google.com/maps/search/?api=1&query=Nescafe&query_place_id=ChIJdcz7ar65vzsRVJoLS_IlVyU'},
 {name:'RC',group:'Outlet',lat:15.392148,lng:73.876219,url:'https://www.google.com/maps/search/?api=1&query=Red+Chillies&query_place_id=ChIJ26KlMzi4vzsRQeuAmpRbKzc',note:'Listed as Red Chillies'},
 {name:'Subspot',group:'Outlet',lat:15.3914736,lng:73.8807144,url:'https://www.google.com/maps/search/?api=1&query=Subspot&query_place_id=ChIJM17AZ1-5vzsRutyOrVBfEXE',note:'Listed as Subspot'},
 {name:'IC',group:'Outlet',lat:15.3929638,lng:73.8803091,url:'https://www.google.com/maps/search/?api=1&query=Institute+Cafeteria&query_place_id=ChIJC8gCTja4vzsRQKZVW64LaNE',note:'Listed as Institute Cafeteria'},
 {name:'A Mess / ANC',group:'Mess',lat:15.3914142,lng:73.8779749,url:'https://www.google.com/maps/search/?api=1&query=Vinayak+Foods+A+Mess+Canteen&query_place_id=ChIJo8xhvKi5vzsRSeMgnlclOlw',note:'Listed as Vinayak Foods A Mess Canteen'},
 {name:'C Mess / CNC',group:'Mess',lat:15.3904186,lng:73.8789602,url:'https://www.google.com/maps/search/?api=1&query=C-Mess&query_place_id=ChIJEc8JgKa5vzsR4H5raT6pLDE'},
 {name:'D Mess / DNC',group:'Mess',lat:15.3928135,lng:73.8841392,url:'https://www.google.com/maps/search/?api=1&query=D+Mess&query_place_id=ChIJ1YvqZAC5vzsRZRtyCraehuY'}
];
const pinLabels=['GL','FK','INS','NES','RC','Subspot','IC','A/ANC','C/CNC','D/DNC'];
const ZMIN=0,ZMAX=19,HOME={lat:15.3918,lng:73.8799};
const merc=(lat:number,lng:number,z:number)=>({x:(lng+180)/360*256*2**z,y:(1-Math.asinh(Math.tan(Math.max(-85,Math.min(85,lat))*Math.PI/180))/Math.PI)/2*256*2**z});
const unmerc=(x:number,y:number,z:number)=>({lng:x/(256*2**z)*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/(256*2**z))))*180/Math.PI});
function positions(width:number,height:number,center:{lat:number,lng:number},zoom:number){const c=merc(center.lat,center.lng,zoom);const pts=pins.map(p=>{const q=merc(p.lat,p.lng,zoom);return {x:width/2+q.x-c.x,y:height/2+q.y-c.y,ox:width/2+q.x-c.x,oy:height/2+q.y-c.y}});
 if(zoom>=14)for(let k=0;k<30;k++){for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j];let dx=b.x-a.x,dy=b.y-a.y;const dist=Math.hypot(dx,dy);if(dist<48){if(dist<0.1){dx=(j-i)%2?1:-1;dy=1}const d=Math.hypot(dx,dy),step=(48-dist)/2;a.x-=dx/d*step;a.y-=dy/d*step;b.x+=dx/d*step;b.y+=dy/d*step}}for(const a of pts){a.x+=(a.ox-a.x)*.015;a.y+=(a.oy-a.y)*.015}}return pts}
export function MapPanel(){const [selected,setSelected]=useState<Pin>(pins[0]);const [zoom,setZoom]=useState(15);const [center,setCenter]=useState(HOME);const [size,setSize]=useState({width:300,height:225});const [expanded,setExpanded]=useState(false);const plot=useRef<HTMLDivElement>(null),root=useRef<HTMLElement>(null),pointers=useRef(new Map<number,{x:number,y:number}>()),lastPinch=useRef<number|null>(null);
 useEffect(()=>{if(!plot.current)return;const ro=new ResizeObserver(([entry])=>setSize({width:entry.contentRect.width,height:entry.contentRect.height}));ro.observe(plot.current);return ()=>ro.disconnect()},[expanded]);
 useEffect(()=>{const onFull=()=>{if(!document.fullscreenElement&&expanded)setExpanded(false)};document.addEventListener('fullscreenchange',onFull);return ()=>document.removeEventListener('fullscreenchange',onFull)},[expanded]);
 const open=()=>{setExpanded(true);const el=root.current;try{void el?.requestFullscreen?.().catch(()=>{})}catch{}};
 const close=()=>{if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});setExpanded(false);setCenter(HOME);setZoom(15)};
 const effective=zoom===14?16:zoom>=15?Math.max(zoom,17+Math.log2(Math.max(size.width/946,size.height/702))):zoom;
 const move=(dx:number,dy:number)=>{const c=merc(center.lat,center.lng,effective),next=unmerc(c.x-dx,c.y-dy,effective);setCenter({lat:Math.max(-82,Math.min(82,next.lat)),lng:Math.max(-180,Math.min(180,next.lng))})};
 const setLevel=(next:number)=>setZoom(Math.max(ZMIN,Math.min(ZMAX,Math.round(next))));
 const pts=positions(size.width,size.height,center,effective),c=merc(center.lat,center.lng,effective);const imgX=size.width/2-c.x+92433*256*2**(effective-17),imgY=size.height/2-c.y+59862*256*2**(effective-17),imgW=1024*2**(effective-17),imgH=768*2**(effective-17),surroundX=size.width/2-c.x+46215*256*2**(effective-16),surroundY=size.height/2-c.y+29929*256*2**(effective-16),surroundSize=1280*2**(effective-16),worldW=256*2**zoom;
 return <section className={'map-panel '+(expanded?'map-expanded':'')} ref={root} aria-label="Campus food map"><div className="map-intro"><p>Campus pin map</p><small>{expanded?'Drag, pinch or scroll to explore. Tap a pin for its place card.':'Tap the map to explore full screen. All ten food pins are on campus.'}</small></div><div className="map-stage"><div className="campus-plot interactive" ref={plot} role="group" aria-label="Interactive map of food locations" onClick={()=>{if(!expanded)open()}} onWheel={e=>{if(!expanded)return;e.preventDefault();setLevel(zoom+(e.deltaY<0?1:-1))}} onPointerDown={e=>{if(!expanded||(e.target as HTMLElement).closest('button'))return;plot.current?.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY})}} onPointerMove={e=>{if(!expanded)return;const old=pointers.current.get(e.pointerId);if(!old)return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const pp=[...pointers.current.values()];if(pp.length===1){move(e.clientX-old.x,e.clientY-old.y)}else if(pp.length===2){const d=Math.hypot(pp[0].x-pp[1].x,pp[0].y-pp[1].y);if(lastPinch.current&&Math.abs(d-lastPinch.current)>22){setLevel(zoom+(d>lastPinch.current?1:-1));lastPinch.current=d}else if(!lastPinch.current)lastPinch.current=d}}} onPointerUp={e=>{pointers.current.delete(e.pointerId);lastPinch.current=null}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);lastPinch.current=null}}>
 {zoom<14&&[-1,0,1].map(n=><img key={n} className="map-world" src={worldMap} alt="" draggable={false} style={{left:size.width/2-merc(center.lat,center.lng,zoom).x+n*worldW,top:size.height/2-merc(center.lat,center.lng,zoom).y,width:worldW,height:worldW}}/>)}{zoom>=14&&<><img className="map-campus-backdrop" src={surroundingMap} alt="" draggable={false} style={{left:surroundX,top:surroundY,width:surroundSize,height:surroundSize}}/><img className="map-campus" src={mapImage} alt="" draggable={false} style={{left:imgX,top:imgY,width:imgW,height:imgH}}/></>}
 {zoom>=14?<><svg className="map-leaders" width={size.width} height={size.height} aria-hidden="true">{pts.map((p,i)=>Math.hypot(p.x-p.ox,p.y-p.oy)>3?<line key={i} x1={p.ox} y1={p.oy} x2={p.x} y2={p.y} stroke="#5f526b" strokeWidth="1"/>:null)}</svg>{pins.map((p,i)=><button key={p.name} type="button" className={'map-marker '+(p.group==='Mess'?'mess-pin ':'')+(selected.name===p.name?'chosen':'')} style={{left:pts[i].x,top:pts[i].y,display:pts[i].x>-12&&pts[i].x<size.width+12&&pts[i].y>-12&&pts[i].y<size.height+12?'':'none'}} onClick={e=>{e.stopPropagation();setSelected(p)}} aria-label={'Show '+p.name} aria-pressed={selected.name===p.name}><span>{pinLabels[i]}</span></button>)}</>:<button className="map-campus-link" type="button" style={{left:pts[0].x,top:pts[0].y}} onClick={()=>{setCenter(HOME);setZoom(15)}}>BITS Goa · 10 food pins</button>}
 <span className="map-attribution">© OpenStreetMap contributors</span>{!expanded&&<span className="map-open">Tap to explore ↗</span>}{expanded&&<><div className="map-controls"><button type="button" onClick={()=>setLevel(zoom+1)} aria-label="Zoom in">+</button><button type="button" onClick={()=>setLevel(zoom-1)} aria-label="Zoom out">−</button><button type="button" onClick={()=>{setCenter(HOME);setZoom(15)}} aria-label="Return to campus">⌖</button></div><span className="map-zoom">Zoom {zoom}</span><button className="map-close" type="button" onClick={close} aria-label="Close map">✕ <span>Close</span></button></>}</div>{expanded&&<div className="map-overlay-card"><strong>{selected.name}</strong><span>{selected.group}{selected.note?' · '+selected.note:''}</span><a href={selected.url} target="_blank" rel="noopener noreferrer">Open place in Google Maps ↗</a></div>}</div>
 {!expanded&&<><div className="map-selected"><strong>{selected.name}</strong><span>{selected.group}{selected.note?' · '+selected.note:''}</span><a href={selected.url} target="_blank" rel="noopener noreferrer">Open place in Google Maps ↗</a></div><div className="map-list">{pins.map((p,i)=><button key={p.name} type="button" onClick={()=>setSelected(p)} aria-pressed={selected.name===p.name} className={selected.name===p.name?'chosen':''}><span>{pinLabels[i]}</span>{p.name}</button>)}</div><p className="map-caveat">A, C and D Mess become ANC, CNC and DNC at night. Pins lead to map listings, not independently confirmed canteen entrances. The app's one mess menu is not assigned to a hall. Beyond campus zoom, the offline world view is an overview, not a street map.</p><p className="map-credit">Map © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a>. Pin locations from Google Maps place listings.</p></>}</section>}
